// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StreetOutlaws.Data.Context;

#nullable disable

namespace StreetOutlaws.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StreetOutlaws.Data.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DriverId = 1,
                            Make = "Pontiac",
                            Model = "GTO",
                            Year = 1970
                        },
                        new
                        {
                            Id = 2,
                            DriverId = 2,
                            Make = "Chevy",
                            Model = "Camero",
                            Year = 1969
                        },
                        new
                        {
                            Id = 3,
                            DriverId = 3,
                            Make = "Chevy",
                            Model = "Camero",
                            Year = 1999
                        },
                        new
                        {
                            Id = 4,
                            DriverId = 4,
                            Make = "Chevy",
                            Model = "Camero",
                            Year = 2010
                        },
                        new
                        {
                            Id = 5,
                            DriverId = 5,
                            Make = "Chevrolet",
                            Model = "Chevy II Nova",
                            Year = 1963
                        },
                        new
                        {
                            Id = 6,
                            DriverId = 6,
                            Make = "Chevrolet",
                            Model = "Chevy II Nova",
                            Year = 1965
                        },
                        new
                        {
                            Id = 7,
                            DriverId = 7,
                            Make = "Chevrolet",
                            Model = "El Camino",
                            Year = 1969
                        },
                        new
                        {
                            Id = 8,
                            DriverId = 8,
                            Make = "Chevrolet",
                            Model = "El Camino",
                            Year = 1981
                        },
                        new
                        {
                            Id = 9,
                            DriverId = 9,
                            Make = "Pontiac",
                            Model = "LeMans",
                            Year = 1969
                        },
                        new
                        {
                            Id = 10,
                            DriverId = 10,
                            Make = "Pontiac",
                            Model = "LeMans",
                            Year = 1972
                        },
                        new
                        {
                            Id = 11,
                            DriverId = 11,
                            Make = "Chevrolet",
                            Model = "Vega",
                            Year = 1977
                        },
                        new
                        {
                            Id = 12,
                            DriverId = 12,
                            Make = "Chevrolet",
                            Model = "C10",
                            Year = 1970
                        },
                        new
                        {
                            Id = 13,
                            DriverId = 13,
                            Make = "Chevrolet",
                            Model = "Monte Carlo",
                            Year = 1971
                        },
                        new
                        {
                            Id = 14,
                            DriverId = 14,
                            Make = "Dodge",
                            Model = "Dart",
                            Year = 1967
                        },
                        new
                        {
                            Id = 15,
                            DriverId = 15,
                            Make = "Ford",
                            Model = "Mustang",
                            Year = 1981
                        },
                        new
                        {
                            Id = 16,
                            DriverId = 16,
                            Make = "Ford",
                            Model = "Mustang",
                            Year = 2010
                        });
                });

            modelBuilder.Entity("StreetOutlaws.Data.Entities.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "DeJuan Colbert",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Zachary Himes",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jordan Hershberger",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Brody Hinton",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Darneisha Miller",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cory Smith",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Jamie Coakley",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "Michael Kinsey",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "Celio Arias",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 10,
                            Name = "Cassandra Emery",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 11,
                            Name = "Catlin Simon",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 12,
                            Name = "Terry Brown",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 13,
                            Name = "Nelson Fant IV",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 14,
                            Name = "Charles Lipperd",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 15,
                            Name = "Adam Lair",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 16,
                            Name = "Katelyn Hedlund",
                            TeamId = 4
                        });
                });

            modelBuilder.Entity("StreetOutlaws.Data.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fire"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Water"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Wind"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Earth"
                        });
                });

            modelBuilder.Entity("StreetOutlaws.Data.Entities.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Indianapolis,Indiana"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Detroit,Michigan"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chicago,Illinois"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Columbus,Ohio"
                        });
                });

            modelBuilder.Entity("StreetOutlaws.Data.Entities.Car", b =>
                {
                    b.HasOne("StreetOutlaws.Data.Entities.Driver", "Driver")
                        .WithMany("Cars")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("StreetOutlaws.Data.Entities.Driver", b =>
                {
                    b.HasOne("StreetOutlaws.Data.Entities.Team", "Team")
                        .WithMany("Drivers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("StreetOutlaws.Data.Entities.Driver", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("StreetOutlaws.Data.Entities.Team", b =>
                {
                    b.Navigation("Drivers");
                });
#pragma warning restore 612, 618
        }
    }
}
